# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1f5d05a2543bf6971bd05151d779aa32466de6b3cf91f475685aa29fd07d02f11d5a971b272f6762e1a1d2c1de5e492071bcf142dc54b6c8580376ae4fd58ff

test:
  secret_key_base: dde0567aacc39bd73dce347d6e47a9bebce34c751167636a5244181560cb0a95b9ab7dc3d9e95ddbbf4e55f87258c86d384a38d0af2fa6ef3a8b5e691352c17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
